language: python
python:
    - 3.5
    - 3.6
env:
    - DJANGO="2.0"
    - DJANGO="2.1"
matrix:
    include:
        - python: "3.7"
          env: DJANGO="2.0"
          dist: xenial
          sudo: true
        - python: "3.7"
          env: DJANGO="2.1"
          dist: xenial
          sudo: true
install:
    - pip install -r requirements.txt
script:
    - python runtests.py
