language: python
dist: xenial

python:
    - 3.5
    - 3.6
    - 3.7

env:
    - DJANGO="2.0"
    - DJANGO="2.1"
    - DJANGO="2.2"

matrix:
    fast_finish: true
    include:
        - { python: "3.6", env: DJANGO=master }
        - { python: "3.7", env: DJANGO=master }
    allow_failures:
        - env: DJANGO="2.2"
        - env: DJANGO=master

install:
    - pip install tox tox-venv tox-travis

script:
    - tox
